# Generated by Django 2.2.4 on 2019-08-15 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190815_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='privateKey',
            new_name='private_key',
        ),
    ]
